### ISSUE TITLE
Handle FetchPolicy in toJson()

### ISSUE THREAD

**Issue by friebetill** [gql-dart/ferry#162]
Currently there is the following exception when trying to convert a request with `FetchPolicy` to json:

<details><summary>Exception</summary>
<p>

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: No serializer for 'FetchPolicy'.
#0      BuiltJsonSerializers._serialize
#1      BuiltJsonSerializers.serialize
#2      BuiltJsonSerializers._serialize
#3      BuiltJsonSerializers.serialize
#4      _$GPokemonDetailReqSerializer.serialize
#5      BuiltJsonSerializers._serialize
#6      BuiltJsonSerializers.serialize
#7      BuiltJsonSerializers.serializeWith
#8      GPokemonDetailReq.toJson
#9      main
<asynchronous suspension>
#10     _runMainZoned.<anonymous closure>.<anonymous closure>                    (dart:ui/hooks.dart:231:25)
#11     _rootRun                                                              (dart:async/zone.dart:1190:13)
#12     _CustomZone.run                                                       (dart:async/zone.dart:1093:19)
#13     _runZoned                                                             (dart:async/zone.dart:1630:10)
#14     runZonedGuarded                                                       (dart:async/zone.dart:1618:12)
#15     _runMainZoned.<anonymous closure>                                         (dart:ui/hooks.dart:223:5)
#16     _startIsolate.<anonymous closure>                     (dart:isolate-patch/isolate_patch.dart:301:19)
#17     _RawReceivePortImpl._handleMessage                    (dart:isolate-patch/isolate_patch.dart:168:12)
```
</p>
</details>

<details><summary>Minimal example based on example</summary>
<p>

```dart
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:ferry/ferry.dart';

import './src/client.dart';
import './src/app.dart';
import 'src/graphql/pokemon_detail.req.gql.dart';

void main() async {
  final client = await initClient();
  GetIt.I.registerLazySingleton<Client>(() => client);

  print(GPokemonDetailReq((b) => b.fetchPolicy = FetchPolicy.CacheAndNetwork)
      .toJson());

  runApp(App());
}
```
</p>
</details>

**Comment by smkhalsa** [comment]
Ah, good catch. We should probably convert FetchPolicy into a `built_value` [enum class](https://github.com/google/built_value.dart#enum-class).

In the meantime, you should be able to create a [custom serializer](https://ferrygraphql.com/docs/custom-scalars#create-a-custom-serializer) manually and include it in your `build.yaml`
