### ISSUE TITLE
Unknown error in BuiltValueGenerator 

### ISSUE THREAD

**Issue by ed-k9** [gql-dart/ferry#213]
Hello, Thanks for the awesome library. 

I'm working with a pretty large schema, almost 10K lines. https://graphql.bitquery.io 

I keep on getting an error when running the generator, No idea what I could be doing wrong or if it is some specific to do with
the schema file.

```
[SEVERE] built_value_generator:built_value on lib/schema.schema.gql.dart (cached):
Unknown error in BuiltValueGenerator for /MY_PACKAGE_NAME/lib/schema.schema.gql.dart.
NoSuchMethodError: The getter 'node' was called on null.
Receiver: null
Tried calling: node

```

**Comment by smkhalsa** [comment]
Hi there. I recommend running the build command in debug mode. It's difficult to provide any insight on this specifically, especially considering the size of your schema.

**Comment by ed-k9** [comment]
@smkhalsa I ran `build_runner` with `-v` is this correct? I don't see anything in particular.

```
[SEVERE] built_value_generator:built_value on lib/schema.schema.gql.dart (cached):
Unknown error in BuiltValueGenerator for /MY_PACKAGE_NAME/lib/schema.schema.gql.dart.
NoSuchMethodError: The getter 'node' was called on null.
Receiver: null
Tried calling: node
dart:core                                                         Object.noSuchMethod
package:built_value_generator/src/enum_source_class.dart 68:62    EnumSourceClass.valuesIdentifier
package:built_value_generator/src/enum_source_class.g.dart 57:63  _$EnumSourceClass.valuesIdentifier
package:built_value_generator/src/enum_source_class.dart 101:8    EnumSourceClass.identifiers
package:built_value_generator/src/enum_source_class.g.dart 70:63  _$EnumSourceClass.identifiers
package:built_value_generator/src/enum_source_library.dart 85:42  EnumSourceLibrary._checkIdentifiers
package:built_value_generator/src/enum_source_library.dart 65:7   EnumSourceLibrary._computeErrors
package:built_value_generator/src/enum_source_library.dart 56:18  EnumSourceLibrary.generateCode
package:built_value_generator/built_value_generator.dart 42:58    BuiltValueGenerator.generate
package:source_gen/src/builder.dart 328:23                        _generate

[SEVERE] Build:
Failed after 11.9s
[+17729 ms] "flutter run" took 17,924ms.
[   +7 ms] pub finished with exit code 1
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:368:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:241:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
     
```

**Comment by smkhalsa** [comment]
Not the verbose flag. You'll want to run the builder in debug mode, so you can break on the actual exception.

**Comment by ed-k9** [comment]
Seems like I'm getting the exception on a few enums 

```
enum SmartContractArgumentsUniq {
  """Unique signatures count"""
  signatures

  """Unique values"""
  values

  """Calls or events"""
  calls

  """Unique transactions count"""
  txs

  """Unique transaction senders"""
  senders

  """Unique callers count"""
  callers

  """Unique smart contracts count"""
  smart_contracts

  """Unique blocks"""
  blocks

  """Unique date count"""
  dates
}

```

<img width="756" alt="Screen Shot 2021-07-01 at 21 43 39" src="https://user-images.githubusercontent.com/84037148/124143659-80d04280-dab5-11eb-980e-cf29a2eb6c28.png">

**Comment by smkhalsa** [comment]
Ah, that makes sense since `values` is used by the dart class to refer to the set of values, which would cause a collision.

We can probably get around this particular error by adding `values` to the [`_reserved`](https://github.com/gql-dart/gql/blob/79735f5bff2b8adc7fabf346874a5f063e9356a3/codegen/gql_code_builder/lib/src/common.dart#L8) list in `gql_code_builder`. 

I made a PR for this. Please confirm whether this resolves the issue.

https://github.com/gql-dart/gql/pull/247/files

**Comment by ed-k9** [comment]
@smkhalsa Yes confirmed it works fine now with your patch
