### ISSUE TITLE
Getting null data for specific query

### ISSUE THREAD

**Issue by dokumanx** [gql-dart/ferry#244]
Hi, I am getting null response below query with ferry. I can get correct data within playground but ferry. I have tried different approaches but without an error it is hard to catch what is going on. If anyone has an idea please leave a comment.

**Query**

```graphql

query StudentNotification($id: Id!) {
    student(studentId: $id) {
        notifications {
            id
            userId
            data
            status
            createdAt
        }
    }
}

```

**Dart code that returns null data**
```dart
Future<List<GStudentNotificationData_student_notifications>>
      getStudentNotifications({required String userId}) async {
    late final OperationResponse response;
    try {
      final studentNotificationsReq =
          GStudentNotificationReq((q) => q..vars.id.value = userId);

      response = await graphQlClient.request(studentNotificationsReq).first;
      print('THIS IS NOTIFICATION RESPONSE: $response');

      return [];
      // return response.data.student.notifications.toList()!;
    } catch (e) {
      print(response.graphqlErrors);
      throw Exception(e.toString());
    }
  }

```

**Debug console**

![image](https://user-images.githubusercontent.com/48089386/130856185-85be0a45-c5ce-4ec4-bd2e-e02eca7d72ba.png)

**Comment by smkhalsa** [comment]
@dokumanx in the debug console you posted, there was a linkException. Can you post the full exception?

**Comment by dokumanx** [comment]
### stackTrace:

```
#0      GJSON.serializer.<anonymous closure> (package:meh/graphql/schema/schema.schema.gql.dart:47:48)
#1      DefaultScalarSerializer.deserialize (package:gql_code_builder/src/serializers/default_scalar_serializer.dart:21:19)
#2      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:184:28)
#3      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)
#4      _$GStudentNotificationData_student_notificationsSerializer.deserialize (package:meh/graphql/schema/queries/student_notifications.data.gql.g.dart:193:43)
#5      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:175:28)
#6      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)
#7      BuiltListSerializer.deserialize.<anonymous closure> (package:built_value/src/built_list_serializer.dart:46:31)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
#10     new List.from (dart:core-patch/array_patch.dart:40:17)
#11     ListBuilder.replace (package:built_collection/src/list/list_builder.dart:44:20)
#12     BuiltListSerializer.deserialize (package:built_value/src/built_list_serializer.dart:45:12)
#13     BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:175:28)
#14     BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)
#15     _$GStudentNotificationData_studentSerializer.deserialize (package:meh/graphql/schema/queries/student_notifications.data.gql.g.dart:118:52)
#16     BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:175:28)
#17     BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)
#18     _$GStudentNotificationDataSerializer.deserialize (package:meh/graphql/schema/queries/student_notifications.data.gql.g.dart:61:46)
#19     BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:175:28)
#20     BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:124:18)
#21     BuiltJsonSerializers.deserializeWith (package:built_value/src/built_json_serializers.dart:42:12)
#22     GStudentNotificationData.fromJson (package:meh/graphql/schema/queries/student_notifications.data.gql.dart:32:12)
#23     GStudentNotificationReq.parseData (package:meh/graphql/schema/queries/student_notifications.req.gql.dart:48:36)
#24     GqlTypedLink.request.<anonymous closure> (package:ferry/src/gql_typed_link.dart:29:42)
#25     _HandlerEventSink.add (dart:async/stream_transformers.dart:209:17)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#27     _rootRunUnary (dart:async/zone.dart:1362:47)
#28     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#31     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#32     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#33     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#34     _rootRun (dart:async/zone.dart:1346:47)
#35     _CustomZone.run (dart:async/zone.dart:1258:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#38     _rootRun (dart:async/zone.dart:1354:13)
#39     _CustomZone.run (dart:async/zone.dart:1258:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

```

### Error Message:

`type 'List<Object?>' is not a subtype of type 'String?' in type cast`

### Error Location in `schema.schema.gql.dart`

```dart
abstract class GJSON implements Built<GJSON, GJSONBuilder> {
  GJSON._();

  factory GJSON([String? value]) =>
      _$GJSON((b) => value != null ? (b..value = value) : b);

  String get value;
  @BuiltValueSerializer(custom: true)
  static Serializer<GJSON> get serializer => _i1.DefaultScalarSerializer<GJSON>(
      (Object serialized) => GJSON((serialized as String?)));
}

```

**Comment by smkhalsa** [comment]
Looks like you're using a custom `JSON` scalar but haven't provided any configuration for it.

Did you follow the instructions in the [docs for custom scalars](https://ferrygraphql.com/docs/custom-scalars)?

**Comment by dokumanx** [comment]
I haven't changed anything for 'JSON'  scalar and it affects only this part. I created a custom scalar for `Upload`. If it is needed, would you mind give me an example for `JSON` scalar? And if you have any idea about why it affects only this part of  the queries I will be appreciated to hear. Thanks for your response.

**Comment by smkhalsa** [comment]
It would only affect this part of the query because it only triggers when trying to deserialize the scalar.

Please read the docs.

https://ferrygraphql.com/docs/custom-scalars#using-structuredserializers

**Comment by dokumanx** [comment]
I read the docs. But still have no clue about creating `StructuredSerializer`. There is no enough example for different usecases. Can you give me an example or even an explanation about how it works and how can we customize it for our needs?

**Comment by chungonion** [comment]
> I read the docs. But still have no clue about creating `StructuredSerializer`. There is no enough example for different usecases. Can you give me an example or even an explanation about how it works and how can we customize it for our needs?

Basically, to my understanding, you would have to create a Model class in your dart project, then specify how will the json object http response in _plain text_ will be converted into your own dart classes. This the process known as serialization and deserialization.

If you wish, you may also refer to `json_serializable` package for less of a hassle on performing serialization and deserialization actions.

**Comment by smkhalsa** [comment]
> If you wish, you may also refer to json_serializable package for less of a hassle on performing serialization and deserialization actions.

ferry expects built_value serializers, so you won't be able to use json_serializable

**Comment by smkhalsa** [comment]
> I read the docs. But still have no clue about creating `StructuredSerializer`. There is no enough example for different usecases. Can you give me an example or even an explanation about how it works and how can we customize it for our needs?

I suggest asking for help on the discord
