### ISSUE TITLE
Union type issue for flutter web on release build mode

### ISSUE THREAD

**Issue by dioseltorre** [gql-dart/ferry#319]
When running the release build for flutter web, this JS error has occurred. Our graphql api returns a union type (please see schema below).
```
main.dart.js:4234 Uncaught TypeError: Instance of 'minified:H0': type 'minified:H0' is not a subtype of type 'minified:ka'
    at Object.c (main.dart.js:4234:3)
    at Object.aMC (main.dart.js:4856:18)
    at kz.b1i [as a] (main.dart.js:4851:3)
    at kz.b1x (main.dart.js:4823:10)
    at main.dart.js:78762:13
    at az2.a (main.dart.js:5427:62)
    at az2.$2 (main.dart.js:39326:14)
    at Object.I (main.dart.js:5413:10)
    at as0.WN (main.dart.js:78796:10)
    at as0.$1 (main.dart.js:78751:19)
```

The issue occurred after executing this request,

```
client.request(request).listen((res) async {
      if (res.hasErrors) {
        ....
        return;
      }

      final data = res.data?.finishMemberLogin;
      if (data?.G__typename == 'MemberSession') {
        final res = data as GFinishMemberLoginData_finishMemberLogin__asMemberSession;
        ....
      } else if (data?.G__typename == 'MemberEmailRegistration') {
        final res = data as GFinishMemberLoginData_finishMemberLogin__asMemberEmailRegistration;
        ...
      }
    });
```

When I logged the `data` from the response above, I only got this information.
```
GFinishMemberLoginData {
  G__typename=GuestMutation,
  finishMemberLogin=GFinishMemberLoginData_finishMemberLogin__base {
    G__typename=MemberSession,
  },
}
```

Mutation
```
mutation FinishMemberLogin($token: String!, $pin: String!) {
  finishMemberLogin(token: $token, pin: $pin) {
    ... on MemberEmailRegistration {
      __typename
      somefield
    }
    ... on MemberSession {
      __typename
      somefield
    }
  }
}
```

Schema
```
type Mutation {
  finishMemberLogin(token: String!, pin: String!): MemberLoginResult!
}

union MemberLoginResult = MemberSession | MemberEmailRegistration
```

Anyone have an idea regarding this issue?

**Comment by sebastianandreasson** [comment]
I'm also seeing this issue on web in release mode, does anyone know a workaround?

**Comment by bgparkerdev** [comment]
Running into this also.

**Comment by Rydeard** [comment]
Running into the same issue now while trying to port our production app to web.

Has anyone been able to patch this?

@smkhalsa I understand you've been busy with other projects, but could you share your thoughts on what might be causing this issue?
