### ISSUE TITLE
Incorrect parser response

### ISSUE THREAD

**Issue by vadimlukutin** [gql-dart/ferry#450]
I was have error on request for data structure. 

[log] DEBUG 2022-12-04 00:59:46.539828:: GraphQL API Request QUERY AddCartItem
[log] DEBUG 2022-12-04 00:59:46.541269:: GraphQL API Request HEADERS {user-id: 914c20e2-1554-4458-869a-52761fd7f81f}
[log] DEBUG 2022-12-04 00:59:46.542483:: GraphQL API Request VARIABLES GAddCartItemVars {
  cartId=07faeffb-833e-4cf9-be9b-cdc7e01578c5,
  data=GCartItemData {
    cartItemConfigurationDataList=[GCartItemConfigurationData {
      comment=,
      optionalModificatorIdList=[],
      qty=1,
      requiredModificatorList=[],
    }],
    productId=c5a59d1b-0341-4b75-9cee-00a57eee981b,
  },
}
[log] ERROR 2022-12-04 00:59:46.566488:: LinkException(type '_$GCartItemData' is not a subtype of type 'GCartItemData' of 'object', #0      _$GCartItemDataSerializer.serialize (package:holla_client/core/data/remote/fragment/__generated__/cart_item.data.gql.g.dart)
#1      BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:103:18)
#2      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:69:18)
#3      _$GAddCartItemVarsSerializer.serialize (package:holla_client/core/data/remote/mutation/__generated__/cart.var.gql.g.dart:33:19)
#4      BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:103:18)
#5      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:69:18)
#6      BuiltJsonSerializers.serializeWith (package:built_value/src/built_json_serializers.dart:53:12)
#7      GAddCartItemVars.toJson (package:holla_client/core/data/remote/mutation/__generated__/cart.var.gql.dart:25:53)
#8      GAddCartItemReq.execRequest (package:holla_client/core/data/remote/mutation/__generated__/cart.req.gql.dart:42:25)

**Comment by knaeckeKami** [comment]
There seems to be an exception when serializing the request to JSON, so the issue occurs not in the response, but before even sending it.
To you have custom scalars/serializers? 
Can you provide a reproducible example?
